management-api:
  image:
    tag: 7.1.3
experience-api:
  image:
    tag: v3.2.2
scheme-adapter:
  sdk-scheme-adapter-api-svc:
    image:
      tag: v24.19.0
ttk:
  ml-testing-toolkit-backend:
    image:
      tag: v18.17.0
    config_files:
      rules_response__default.json: https://raw.githubusercontent.com/infitx-org/comesa-tests/refs/tags/v1.17.18/ttk-rules/sync-response-rules.json
  ml-testing-toolkit-frontend:
    image:
      tag: v16.7.4
frontend:
  image:
    repository: pm4ml/mojaloop-payment-manager-ui
    tag: 1.20.0
