_DEFINE:
  CONTINUOUS_DEPLOYMENT:
    management-api: &management-api
      image:
        tag: 7.2.0-infitx.4
inter-scheme-proxy-adapter:
  image:
    tag: v1.9.0-infitx.1
    registry: docker.io
    repository: mojaloop/inter-scheme-proxy-adapter
management-api-a: *management-api
management-api-b: *management-api
