_DEFINE:
  CONTINUOUS_DEPLOYMENT:
    management-api: &management-api
      image:
        tag: 6.11.1
inter-scheme-proxy-adapter:
  image:
    tag: v1.8.1
    registry: docker.io
    repository: mojaloop/inter-scheme-proxy-adapter
management-api-a: *management-api
management-api-b: *management-api
